### ISSUE TITLE
Доступ к репозиторию

### ISSUE THREAD

**Issue by mmaltsev** [t-j-live/forem#7]
Привет @superkeka, github мне пишет что у меня недостаточно прав чтобы менять репозиторий, можешь дать плиз? Я хотел небольшой PR отправить.

И, в принципе, если это будет OpenSource, лучше разрешить всем создавать PR, но не всем мерджить в мастер просто.

**Comment by superkeka** [comment]
Спасибо! Что-то забыл про это. Выдал права.
